### ISSUE TITLE
Multiple issues in doc ipython notebooks

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#3321]
Here is a list of errors I encountered while running the ipython notebooks:
```
============= ./doc/source/quickstart/3)_Simple_Visualization.py ==============
Redshift = -2.7810863612032e-09
Parsing Hierarchy : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 210/211 [00:00<00:00, 7369.26it/s]
<yt.visualization.plot_window.ProjectionPlot object at 0x7f5dfbb8a070>
<yt.visualization.plot_window.ProjectionPlot object at 0x7f5dac758760>
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ccc/Documents/prog/yt/doc/source/quickstart/3)_Simple_Visualization.py:100 in <module>     │
│                                                                                                  │
│    97 # In[ ]:                                                                                   │
│    98                                                                                            │
│    99                                                                                            │
│ ❱ 100 ds = yt.load_sample("Enzo_64", "DD0043/data0043")                                          │
│   101 s = yt.SlicePlot(ds, "z", ["density", "velocity_magnitude"], center="max")                 │
│   102 s.set_cmap("velocity_magnitude", "kamae")                                                  │
│   103 s.zoom(10.0)                                                                               │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/loaders.py:1337 in load_sample                                    │
│                                                                                                  │
│   1334 │   │   mylog.info("Sample dataset found in '%s'", data_dir)                              │
│   1335 │   │   if timeout is not None:                                                           │
│   1336 │   │   │   mylog.info("Ignoring the `timeout` keyword argument received.")               │
│ ❱ 1337 │   │   return load(loadable_path, **kwargs)                                              │
│   1338 │                                                                                         │
│   1339 │   try:                                                                                  │
│   1340 │   │   save_dir = _get_test_data_dir_path()                                              │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/loaders.py:80 in load                                             │
│                                                                                                  │
│     77 │   # This will raise FileNotFoundError if the path isn't matched                         │
│     78 │   # either in the current dir or yt.config.ytcfg['data_dir_directory']                  │
│     79 │   if not fn.startswith("http"):                                                         │
│ ❱   80 │   │   fn = str(lookup_on_disk_data(fn))                                                 │
│     81 │                                                                                         │
│     82 │   candidates = []                                                                       │
│     83 │   for cls in output_type_registry.values():                                             │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/sample_data/api.py:164 in lookup_on_disk_data                     │
│                                                                                                  │
│   161 │                                                                                          │
│   162 │   if not alt_path.exists():                                                              │
│   163 │   │   err_msg += f"\n(Also tried '{alt_path}')."                                         │
│ ❱ 164 │   │   raise FileNotFoundError(err_msg)                                                   │
│   165 │                                                                                          │
│   166 │   return alt_path                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: No such file or directory: '/home/ccc/Documents/prog/yt-data/Enzo_64/None'.

============= ./doc/source/quickstart/4)_Data_Objects_and_Time_Series.py ==============
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ccc/Documents/prog/yt/doc/source/quickstart/4)_Data_Objects_and_Time_Series.py:15 in       │
│ <module>                                                                                         │
│                                                                                                  │
│    12 import yt                                                                                  │
│    13 import numpy as np                                                                         │
│    14 from matplotlib import pylab                                                               │
│ ❱  15 from yt.extensions.astro_analysis.halo_finding.api import HaloFinder                       │
│    16                                                                                            │
│    17                                                                                            │
│    18 # ## Time Series Data                                                                      │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/exthook.py:88 in load_module                                      │
│                                                                                                  │
│    85 │   │   │   if "." not in modname:                                                         │
│    86 │   │   │   │   setattr(sys.modules[self.wrapper_module], modname, module)                 │
│    87 │   │   │   return module                                                                  │
│ ❱  88 │   │   raise ImportError(f"No module named {fullname}")                                   │
│    89 │                                                                                          │
│    90 │   def is_important_traceback(self, important_module, tb):                                │
│    91 │   │   """Walks a traceback's frames and checks if any of the frames                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: No module named yt.extensions.astro_analysis.halo_finding.api

============= ./doc/source/examining/Loading_Spherical_Data.py ==============
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ccc/Documents/prog/yt/doc/source/examining/Loading_Spherical_Data.py:24 in <module>        │
│                                                                                                  │
│    21 # In[ ]:                                                                                   │
│    22                                                                                            │
│    23                                                                                            │
│ ❱  24 @yt.derived_field(name = "sphx", units = "cm", take_log=False)                             │
│    25 def sphx(field, data):                                                                     │
│    26 │   return np.cos(data["phi"]) * np.sin(data["theta"])*data["r"]                           │
│    27 @yt.derived_field(name = "sphy", units = "cm", take_log=False)                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: derived_field() missing 1 required positional argument: 'sampling_type'

============= ./doc/source/examining/Loading_Generic_Particle_Data.py ==============
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ccc/Documents/prog/yt/doc/source/examining/Loading_Generic_Particle_Data.py:43 in <module> │
│                                                                                                  │
│    40                                                                                            │
│    41 bbox = 1.1*np.array([[min(ppx), max(ppx)], [min(ppy), max(ppy)], [min(ppz), max(ppz)]])    │
│    42                                                                                            │
│ ❱  43 ds = yt.load_particles(data, length_unit=parsec, mass_unit=1e8*Msun, n_ref=256, bbox=bbo   │
│    44                                                                                            │
│    45                                                                                            │
│    46 # The `length_unit` and `mass_unit` are the conversion from the units used in the `data`   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: load_particles() got an unexpected keyword argument 'n_ref'

============= ./doc/source/visualizing/Volume_Rendering_Tutorial.py ==============
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ccc/Documents/prog/yt/doc/source/visualizing/Volume_Rendering_Tutorial.py:24 in <module>   │
│                                                                                                  │
│    21 import yt                                                                                  │
│    22 import numpy as np                                                                         │
│    23 from yt.visualization.volume_rendering.transfer_function_helper import TransferFunctionH   │
│ ❱  24 from yt.visualization.volume_rendering.api import Scene, VolumeSource                      │
│    25                                                                                            │
│    26 ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")                                       │
│    27 sc = yt.create_scene(ds)                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'VolumeSource' from 'yt.visualization.volume_rendering.api' (/home/ccc/Documents/prog/yt/yt/visualization/volume_rendering/api.py)

============= ./doc/source/cookbook/yt_gadget_owls_analysis.py ==============
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ccc/Documents/prog/yt/doc/source/cookbook/yt_gadget_owls_analysis.py:42 in <module>        │
│                                                                                                  │
│    39                                                                                            │
│    40                                                                                            │
│    41 fname = 'snapshot_033/snap_033.0.hdf5'                                                     │
│ ❱  42 ds = yt.load(fname, n_ref=64, over_refine_factor=1)                                        │
│    43                                                                                            │
│    44                                                                                            │
│    45 # Set a ``YTRegion`` that contains all the data.                                           │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/loaders.py:91 in load                                             │
│                                                                                                  │
│     88 │   candidates = find_lowest_subclasses(candidates)                                       │
│     89 │                                                                                         │
│     90 │   if len(candidates) == 1:                                                              │
│ ❱   91 │   │   return candidates[0](fn, *args, **kwargs)                                         │
│     92 │                                                                                         │
│     93 │   if len(candidates) > 1:                                                               │
│     94 │   │   raise YTAmbiguousDataType(fn, candidates)                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: __init__() got an unexpected keyword argument 'n_ref'

============= ./doc/source/analyzing/particle_filter.py ==============
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ccc/Documents/prog/yt/doc/source/analyzing/particle_filter.py:76 in <module>               │
│                                                                                                  │
│   73 # In[ ]:                                                                                    │
│   74                                                                                             │
│   75                                                                                             │
│ ❱ 76 p = yt.ProjectionPlot(ds, 'z', [('deposit', 'young_stars_cic'), ('deposit', 'old_stars_c    │
│   77 p.set_figure_size(5)                                                                        │
│   78 p.show()                                                                                    │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/visualization/plot_window.py:1827 in __init__                     │
│                                                                                                  │
│   1824 │   │   │   │   method=method,                                                            │
│   1825 │   │   │   │   max_level=max_level,                                                      │
│   1826 │   │   │   )                                                                             │
│ ❱ 1827 │   │   PWViewerMPL.__init__(                                                             │
│   1828 │   │   │   self,                                                                         │
│   1829 │   │   │   proj,                                                                         │
│   1830 │   │   │   bounds,                                                                       │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/visualization/plot_window.py:855 in __init__                      │
│                                                                                                  │
│    852 │   │   if self._plot_type is None:                                                       │
│    853 │   │   │   self._plot_type = kwargs.pop("plot_type")                                     │
│    854 │   │   self._splat_color = kwargs.pop("splat_color", None)                               │
│ ❱  855 │   │   PlotWindow.__init__(self, *args, **kwargs)                                        │
│    856 │                                                                                         │
│    857 │   def _setup_origin(self):                                                              │
│    858 │   │   origin = self.origin                                                              │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/visualization/plot_window.py:241 in __init__                      │
│                                                                                                  │
│    238 │   │   │   self._units_config[field]                                                     │
│    239 │   │                                                                                     │
│    240 │   │   self.setup_callbacks()                                                            │
│ ❱  241 │   │   self._setup_plots()                                                               │
│    242 │                                                                                         │
│    243 │   def __iter__(self):                                                                   │
│    244 │   │   for ds in self.ts:                                                                │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/visualization/plot_window.py:986 in _setup_plots                  │
│                                                                                                  │
│    983 │   │   │   else:                                                                         │
│    984 │   │   │   │   zlim = (None, None)                                                       │
│    985 │   │   │                                                                                 │
│ ❱  986 │   │   │   image = self.frb[f]                                                           │
│    987 │   │   │   if self._field_transform[f] == log_transform:                                 │
│    988 │   │   │   │   msg = None                                                                │
│    989 │   │   │   │   use_symlog = False                                                        │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/visualization/fixed_resolution.py:140 in __getitem__              │
│                                                                                                  │
│   137 │   │   │   │   b = float(b.in_units("code_length"))                                       │
│   138 │   │   │   bounds.append(b)                                                               │
│   139 │   │                                                                                      │
│ ❱ 140 │   │   buff = self.ds.coordinates.pixelize(                                               │
│   141 │   │   │   self.data_source.axis,                                                         │
│   142 │   │   │   self.data_source,                                                              │
│   143 │   │   │   item,                                                                          │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/geometry/coordinates/cartesian_coordinates.py:217 in pixelize     │
│                                                                                                  │
│   214 │   │   │   return np.squeeze(np.transpose(img, (yax, xax, ax)))                           │
│   215 │   │                                                                                      │
│   216 │   │   elif self.axis_id.get(dimension, dimension) < 3:                                   │
│ ❱ 217 │   │   │   return self._ortho_pixelize(                                                   │
│   218 │   │   │   │   data_source, field, bounds, size, antialias, dimension, periodic           │
│   219 │   │   │   )                                                                              │
│   220 │   │   else:                                                                              │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/geometry/coordinates/cartesian_coordinates.py:537 in              │
│ _ortho_pixelize                                                                                  │
│                                                                                                  │
│   534 │   │   else:                                                                              │
│   535 │   │   │   pixelize_cartesian(                                                            │
│   536 │   │   │   │   buff,                                                                      │
│ ❱ 537 │   │   │   │   data_source["px"],                                                         │
│   538 │   │   │   │   data_source["py"],                                                         │
│   539 │   │   │   │   data_source["pdx"],                                                        │
│   540 │   │   │   │   data_source["pdy"],                                                        │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/data_objects/data_containers.py:255 in __getitem__                │
│                                                                                                  │
│    252 │   │   f = self._determine_fields([key])[0]                                              │
│    253 │   │   if f not in self.field_data and key not in self.field_data:                       │
│    254 │   │   │   if f in self._container_fields:                                               │
│ ❱  255 │   │   │   │   self.field_data[f] = self.ds.arr(self._generate_container_field(f))       │
│    256 │   │   │   │   return self.field_data[f]                                                 │
│    257 │   │   │   else:                                                                         │
│    258 │   │   │   │   self.get_data(f)                                                          │
│                                                                                                  │
│ /home/ccc/Documents/prog/yt/yt/data_objects/data_containers.py:422 in _generate_container_field  │
│                                                                                                  │
│    419 │   │   return size                                                                       │
│    420 │                                                                                         │
│    421 │   def _generate_container_field(self, field):                                           │
│ ❱  422 │   │   raise NotImplementedError                                                         │
│    423 │                                                                                         │
│    424 │   def _parameter_iterate(self, seq):                                                    │
│    425 │   │   for obj in seq:                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NotImplementedError: 
```

**Comment by chummels** [comment]
@cphyc I think some of these bugs have already been addressed in my recent docs PRs.  The first two errors are in the quickstart notebooks and they have already been fixed about two weeks ago.  The ones in the cookbook have also already been fixed.  But the ones in the `examining` and `analyzing` have not yet been addressed because those are sections of the docs that have not yet been reviewed.

**Comment by neutrinoceros** [comment]
I recognise a couple of these bugs as things we indeed fixed already. @cphyc , should we close this ?

**Comment by cphyc** [comment]
Let's close and I'll re-open if some of the bugs are still there.
